// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "gcd.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic gcd::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic gcd::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> gcd::ap_ST_fsm_state1 = "1";
const sc_lv<2> gcd::ap_ST_fsm_state2 = "10";
const sc_lv<32> gcd::ap_const_lv32_0 = "00000000000000000000000000000000";
const int gcd::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> gcd::ap_const_lv32_1 = "1";
const sc_lv<1> gcd::ap_const_lv1_0 = "0";
const sc_lv<1> gcd::ap_const_lv1_1 = "1";
const bool gcd::ap_const_boolean_1 = true;

gcd::gcd(sc_module_name name) : sc_module(name), mVcdFile(0) {
    gcd_AXILiteS_s_axi_U = new gcd_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("gcd_AXILiteS_s_axi_U");
    gcd_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    gcd_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    gcd_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    gcd_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    gcd_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    gcd_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    gcd_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    gcd_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    gcd_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    gcd_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    gcd_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    gcd_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    gcd_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    gcd_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    gcd_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    gcd_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    gcd_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    gcd_AXILiteS_s_axi_U->ACLK(ap_clk);
    gcd_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    gcd_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    gcd_AXILiteS_s_axi_U->ap_start(ap_start);
    gcd_AXILiteS_s_axi_U->interrupt(interrupt);
    gcd_AXILiteS_s_axi_U->ap_ready(ap_ready);
    gcd_AXILiteS_s_axi_U->ap_done(ap_done);
    gcd_AXILiteS_s_axi_U->ap_idle(ap_idle);
    gcd_AXILiteS_s_axi_U->a(a);
    gcd_AXILiteS_s_axi_U->b(b);
    gcd_AXILiteS_s_axi_U->c(p_01_reg_43);
    gcd_AXILiteS_s_axi_U->c_ap_vld(c_ap_vld);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_62_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_62_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_c_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_62_p2 );

    SC_METHOD(thread_icmp_ln7_fu_62_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_01_reg_43 );
    sensitive << ( p_0_reg_53 );

    SC_METHOD(thread_icmp_ln8_fu_68_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_62_p2 );
    sensitive << ( p_01_reg_43 );
    sensitive << ( p_0_reg_53 );

    SC_METHOD(thread_select_ln8_1_fu_94_p3);
    sensitive << ( p_0_reg_53 );
    sensitive << ( icmp_ln8_fu_68_p2 );
    sensitive << ( sub_ln9_fu_74_p2 );

    SC_METHOD(thread_select_ln8_fu_86_p3);
    sensitive << ( p_01_reg_43 );
    sensitive << ( icmp_ln8_fu_68_p2 );
    sensitive << ( sub_ln11_fu_80_p2 );

    SC_METHOD(thread_sub_ln11_fu_80_p2);
    sensitive << ( p_01_reg_43 );
    sensitive << ( p_0_reg_53 );

    SC_METHOD(thread_sub_ln9_fu_74_p2);
    sensitive << ( p_01_reg_43 );
    sensitive << ( p_0_reg_53 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_62_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "gcd_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, a, "a");
    sc_trace(mVcdFile, b, "b");
    sc_trace(mVcdFile, c_ap_vld, "c_ap_vld");
    sc_trace(mVcdFile, select_ln8_fu_86_p3, "select_ln8_fu_86_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln7_fu_62_p2, "icmp_ln7_fu_62_p2");
    sc_trace(mVcdFile, select_ln8_1_fu_94_p3, "select_ln8_1_fu_94_p3");
    sc_trace(mVcdFile, p_01_reg_43, "p_01_reg_43");
    sc_trace(mVcdFile, p_0_reg_53, "p_0_reg_53");
    sc_trace(mVcdFile, icmp_ln8_fu_68_p2, "icmp_ln8_fu_68_p2");
    sc_trace(mVcdFile, sub_ln11_fu_80_p2, "sub_ln11_fu_80_p2");
    sc_trace(mVcdFile, sub_ln9_fu_74_p2, "sub_ln9_fu_74_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("gcd.hdltvin.dat");
    mHdltvoutHandle.open("gcd.hdltvout.dat");
}

gcd::~gcd() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete gcd_AXILiteS_s_axi_U;
}

void gcd::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void gcd::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_0))) {
        p_01_reg_43 = select_ln8_fu_86_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_01_reg_43 = b.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_0))) {
        p_0_reg_53 = select_ln8_1_fu_94_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0_reg_53 = a.read();
    }
}

void gcd::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void gcd::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void gcd::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void gcd::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void gcd::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void gcd::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void gcd::thread_c_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_1))) {
        c_ap_vld = ap_const_logic_1;
    } else {
        c_ap_vld = ap_const_logic_0;
    }
}

void gcd::thread_icmp_ln7_fu_62_p2() {
    icmp_ln7_fu_62_p2 = (!p_0_reg_53.read().is_01() || !p_01_reg_43.read().is_01())? sc_lv<1>(): sc_lv<1>(p_0_reg_53.read() == p_01_reg_43.read());
}

void gcd::thread_icmp_ln8_fu_68_p2() {
    icmp_ln8_fu_68_p2 = (!p_0_reg_53.read().is_01() || !p_01_reg_43.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_0_reg_53.read()) > sc_bigint<32>(p_01_reg_43.read()));
}

void gcd::thread_select_ln8_1_fu_94_p3() {
    select_ln8_1_fu_94_p3 = (!icmp_ln8_fu_68_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_fu_68_p2.read()[0].to_bool())? sub_ln9_fu_74_p2.read(): p_0_reg_53.read());
}

void gcd::thread_select_ln8_fu_86_p3() {
    select_ln8_fu_86_p3 = (!icmp_ln8_fu_68_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_fu_68_p2.read()[0].to_bool())? p_01_reg_43.read(): sub_ln11_fu_80_p2.read());
}

void gcd::thread_sub_ln11_fu_80_p2() {
    sub_ln11_fu_80_p2 = (!p_01_reg_43.read().is_01() || !p_0_reg_53.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_01_reg_43.read()) - sc_biguint<32>(p_0_reg_53.read()));
}

void gcd::thread_sub_ln9_fu_74_p2() {
    sub_ln9_fu_74_p2 = (!p_0_reg_53.read().is_01() || !p_01_reg_43.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_0_reg_53.read()) - sc_biguint<32>(p_01_reg_43.read()));
}

void gcd::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_62_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void gcd::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

